name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
      script:
        description: "Specify the build script to run"
        required: false
        default: "yarn build"
      yarn_version:
        required: false
        type: string
        default: "3.6.3"
  

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@7047052a8fdf125cc198b4e66ec99aee5d2b062f
    with:
      tag: "${{ github.event.inputs.tag }}"
      script: "${{ github.event.inputs.script }}"
      yarn_version: "${{ github.event.inputs.yarn_version }}"