name: containerd-releases-json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - '.github/containerd-releases.json'

jobs:
  generate:
    uses: ./.github/workflows/releases-json.yml
    with:
      repository: containerd/containerd
      artifact_name: containerd-releases-json
      filename: containerd-releases.json
    secrets: inherit

  open-pr:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request'
    permissions:
      # required to create PR
      contents: write
      pull-requests: write
    needs:
      - generate
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      -
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      -
        name: Download
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: containerd-releases-json
          path: .github
      -
        name: Commit changes
        run: |
          git add -A .
      -
        name: Create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          base: main
          branch: bot/containerd-releases-json
          commit-message: "update .github/containerd-releases.json"
          signoff: true
          delete-branch: true
          title: "Update `.github/containerd-releases.json`"
          body: |
            Update `.github/containerd-releases.json` to keep in sync with [https://github.com/containerd/containerd](https://github.com/containerd/containerd).
          draft: false
