name: releases-json

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      artifact_name:
        required: false
        type: string
        default: 'releases-json'
      filename:
        required: false
        type: string
        default: 'releases.json'
      pin_latest:
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.generate.outputs.releases }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      -
        name: Install npm deps
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await core.group(`Install npm deps`, async () => {
              await exec.exec('npm', ['install', 'semver']);
            });
      -
        name: Generate
        id: generate
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          retries: 3
          script: |
            const fs = require('fs');
            const semver = require('semver');

            let res = {};
            const [owner, repo] = `${{ inputs.repository }}`.split('/');
            core.info(`Fetching releases for ${owner}/${repo}`);

            const latestRelease = await github.rest.repos.getLatestRelease({
              owner,
              repo,
            });
            res['latest'] = {
              id: latestRelease.data.id,
              tag_name: latestRelease.data.tag_name,
              html_url: latestRelease.data.html_url,
              assets: latestRelease.data.assets.map(asset => asset.browser_download_url).sort(),
            };

            const pinLatest = `${{ inputs.pin_latest }}`;

            const releases = await github.paginate(github.rest.repos.listReleases.endpoint.merge({
              owner,
              repo,
            }));
            for (const release of releases) {
              if (release.draft) {
                continue;
              }
              if (!res['edge'] && release.prerelease) {
                if (semver.gt(release.tag_name, res['latest'].tag_name)) {
                  res['edge'] = {
                    id: release.id,
                    tag_name: release.tag_name,
                    html_url: release.html_url,
                    assets: release.assets.map(asset => asset.browser_download_url).sort(),
                  };
                } else {
                  res['edge'] = res['latest'];
                }
              }
              if (pinLatest && release.tag_name === pinLatest) {
                res['latest'] = {
                  id: release.id,
                  tag_name: release.tag_name,
                  html_url: release.html_url,
                  assets: release.assets.map(asset => asset.browser_download_url).sort(),
                };
              }
              res[release.tag_name] = {
                id: release.id,
                tag_name: release.tag_name,
                html_url: release.html_url,
                assets: release.assets.map(asset => asset.browser_download_url).sort(),
              };
            }

            await fs.writeFileSync('${{ inputs.filename }}', JSON.stringify(res, null, 2));
      -
        name: Check file
        run: |
          jq . ${{ inputs.filename }}
      -
        name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.filename }}
          if-no-files-found: error